# 运行时参数
#===================================
train: Train # 对每个cient训练新的模型或者利用已有模型
predict: Train # 生成新的预测，或者使用本地存储的预测
use_id: "2020-11-01_09.32.00"
random_seed: 0
# 训练参数
# ==================================
batch_size: 16
num_rounds: 100
eval_every: 1
clients_per_round: 10
num_epochs: 50

# 模型参数
# ==================================
seq_len: 10
len_out: 1
##学习率
lr: 0.005
##步长
n_timesteps: 7
##输入的维度
n_dimension: 7
##label的长度
n_label: 7
##label的维度
label_class: 1
##隐藏层单元数
n_hidden: 150

#回归指标
precision_key: 'Precision'
MAE_key: 'MAE'
MSE_key: 'MSE'
RMSE_key: 'RMSE'

# 其他
# ==================================
bytes_written_key: 'bytes_written'
bytes_read_key: 'bytes_read'
local_computations_key: 'local_computations'
num_round_key: 'round_number'
num_samples_key: 'num_samples'
client_id_key: 'client_id'
#=========预测值存储位置======================
metrics_name: 'metrics'

#high
metrics_dir: 'metrics/ener_temp_filter/winter7_choose/high/FL'
#mid
#metrics_dir: 'metrics/ener_temp_filter/winter7_choose/mid/FL'
#low
#metrics_dir: 'metrics/ener_temp_filter/winter7_choose/low/FL'

#=========================================
#数据集位置
#=========================================
train_data_dir: 'data/house_temp_energy_season/winternumpy7_choose/high/train'
test_data_dir: 'data/house_temp_energy_season/winternumpy7_choose/high/test'
#=========================================
# 可选择的模型
LSTM: 'LSTM'
Fed_LSTM: 'Fed_LSTM'

